<?php
/*
	LANGUAGE CONSTANTS
	LANG: ES
*/
define("MENU_MENU","Menú");
define("MENU_HOME","Inicio");
define("MENU_SEARCHER","Buscador");
define("MENU_LEGEND","Leyenda");
define("MENU_INFORMATION","Información");
define("MENU_CONFIGURATION","Configuración");
define("MENU_REPORT","Informe");
define("MENU_CONTACT","Contacto");
define("FORM_NAME_AND_SURNAME","Nombre y Apellidos");
define("FORM_PROVINCE", "Provincia");
define("FORM_COUNTY", "Comarca");
define("FORM_CITY", "Municipio");
define("FORM_INE", "Código INE");
define("FORM_NAME", "Nombre");
define("FORM_EMAIL", "E-mail");
define("FORM_SUBJECT", "Asunto");
define("FORM_MESSAGE", "Mensaje");
define("FORM_SEND", "Enviar");
define("FORM_CANCEL","Cancelar");
define("FORM_SELECT","Seleccionar...");
define("PROVINCE","Província");
define("TOWN","Municipio");
define("COMERCIAL_DATA","Datos Comerciales");
define("SANITY_PROVIDER","Entidad suministradora de saneamiento");
define("CONTRACT_INIT","Fecha de inicio de contrato");
define("CONTRACT_END","Fecha de fin de contrato");
define("SHOW_FORM","Edición");
define("TOWN_DATA","Datos del municipio");
define("BASIC_DATA","Datos Básicos");
define("SURFACE","Superfície (km²)");
define("POPULATION","Habitantes");
define("GOVERNMENT","Equipo de gobierno");
define("WATER_PROVIDER","Entidad suministradora agua potable");
define("CLOSE","Cerrar");
define("CLEAR","Borrar");
define("TODAY","Hoy");
define("CREATE_REPORT","Crear informe");
define("DOWNLOAD_REPORT","Descargar informe");
define("GOVERN","Gobierno");
define("OBSERVATIONS","Observaciones");
define("NO_RESULTS","No hay resultados");
define("BACKGROUND_MAP","Mapa de fondo");
define("BACKGROUND_MAP_1","OpenStreetMap, estilo Positron (by cartoDB)");
define("BACKGROUND_MAP_2","OpenStreetMap, estilo Dak Matter (by CartoDB)");
define("PASSWORD_FORGOT","¿Olvidó su contraseña?");
define("REQUEST","SOLICITAR");
define("INTRODUCE_EMAIL_FOR_PWD_RECOVERY","Introduzca su dirección email para iniciar el proceso de resetear su password");
define("RECOVERY_INSTRUCTIONS","Se ha enviado un mail con las instrucciones y el link para regenerar su password.");
define("NO_USER_IN_DB","No existe el email suministrado");
define("NO_HASH","El link no es válido");
define("PASSWORD1","Introduzca su nuevo password");
define("PASSWORD2","Repita su nuevo password");
define("REGENERATE","REGENERAR");
define("PASSWORD_NOT_MATCH","Los passwords deben ser iguales");
define("PASSWORD_GENERATED_OK","Password regenerado. Puede loginarse normalmente clicando <a href='index.php'>aquí</a>");
define("ALARM_TIME","Periodo de alarma");
define("DRINK_WATER","Agua potable");
define("SIX_MONTHS","6 meses");
define("TEN_MONTHS","10 meses");
define("TWELVE_MONTHS","12 meses");
define("SEE_DRINK_WATER_PROVIDER","entidad suministradora de agua potable");
define("SEE_SANITY_WATER_PROVIDER","entidad gestora del saneamiento");
define("SEE","Ver");
define("NEXT_EXTENSION","Próxima prórroga");
define("NEXT_COMPETITION","Próximo concurso");
define("NEXT_EXTENSIONS","Futuras prórrogas");
define("CARTERA","Cartera Próxima Prórroga");
define("REST","Resto");
define("BUSSINNES_NUMBERS","Cifras de negocio");
define("REQUIRED_INVESTMENT","Inversión Necesaria");
define("TOTAL","Total");
define("MORE","Más");
?>